### ISSUE TITLE
CMakeError when building the project

### ISSUE THREAD

**Issue by Yongze-zzz** [owensgroup/MVGpuBTree#2]
Dear author!Thanks for your great work.When I try to reproduce your experimental results and try to compile MVGpuBtree,the following error after the command(cmake ..)
![image](https://user-images.githubusercontent.com/70116723/210170161-56f10751-96d8-4d49-a150-788de12d9133.png)
I tried to solve it used different versions gcc/g++:tried 9.3 ,7.5,11.3,different cmake version : 3.8,3.16.3,but without any change,solutions did not work.I check my CmakeError.log.It seems like  /usr/bin/ld: cannot find -lpthread.But I don't know the location where I could add -lpthread.
![image](https://user-images.githubusercontent.com/70116723/210170247-8ad0ece7-c7e1-4160-86fb-a3178c2e68a7.png)
What's more,I use 8vCPU 32GiB,GPU:NVIDIA V100,Cuda version:11.4.

Kindly confirm why we are facing this issue?

**Comment by maawad** [comment]
Hi @Yongze-zzz , Could you please upgrade CMake to version 3.18.0 or higher?

**Comment by Yongze-zzz** [comment]
> 你好@Yongze-zzz, 能否请您将 CMake 升级到 3.18.0 或更高版本？

![1672582627262](https://user-images.githubusercontent.com/70116723/210173718-b44cbb5a-f132-4220-bf7b-699eecb592d3.png)
It works.Appreciate!
