### ISSUE TITLE
Question about key and value size in btree

### ISSUE THREAD

**Issue by StarGazerM** [owensgroup/MVGpuBTree#8]
Hi:
    It seems for each k,v pair stored in GpuBTree must have same memory size of type Key and type Value. Why it has to be the same?  Can I use custom data structure with a comparator for key type?

**Comment by maawad** [comment]
Hi @StarGazerM, apologies for the late response. The current implementation was tested on 32-bit keys and 32-bit values only -- so the limitation is the 4-byte key/value, not whether they are the same or not. Although much of the code is templated and generic enough, I didn't test it for 64-bit keys and expect it to break. The main challenge is the node structure and how to pack everything in a cache line. 

Supporting custom structures for keys and values is a different, challenging problem, and I think it would require using locks for all node read operations during traversal (the custom comparator won't be the challenge). 

Modernizing the tree may solve some of these issues and I started some of that effort in [MVGpuBTree/tree/atomic-ref](https://github.com/owensgroup/MVGpuBTree/tree/atomic-ref) but I haven't had the time to finish that.

**Comment by StarGazerM** [comment]
Sounds reasonable to me. So in current design, the "value" is just a pointer/array index to underline data, but not the actual data itself, if I am using this datastructure I still need to manage the actual data myself?

**Comment by StarGazerM** [comment]
but seems in this case, , when the data grows, in order to make sure original indexing in btree is not messed up, underline data must be append only. the comparator will cause non-coleasing memory access when after certain times of inserting .I still need reconstruct whole BTree? seems some kind of fall back  to LSM like datastructure.

**Comment by maawad** [comment]
> Sounds reasonable to me. So in current design, the "value" is just a pointer/array index to underline data, but not the actual data itself, if I am using this datastructure I still need to manage the actual data myself?

Correct. If you need to work with values larger than the supported value type size, you can always store a pointer to your actual value.

> but seems in this case, , when the data grows, in order to make sure original indexing in btree is not messed up, underline data must be append only. the comparator will cause non-coleasing memory access when after certain times of inserting .I still need reconstruct whole BTree? seems some kind of fall back to LSM like datastructure.

If at some point you need to reorganize your values data structure, you don't need to reconstruct the tree, you just need to update the values ("pointers"). I think any decision you make should depend on your workload (e.g., how often you insert/update new/existing values, are the values already stored in some secondary data structure, how often you do queries, what kind of query, what are the batch sizes for updates and queries and so on).

**Comment by StarGazerM** [comment]
this is great. If I want to customize comparator, could you please guide me a little, which part of code should I look into?

**Comment by maawad** [comment]
Comparisons are performed inside the [node structure](https://github.com/owensgroup/MVGpuBTree/blob/main/include/node.hpp). You would need to add a template parameter for the comparator and propagate all the way down to the node structure and then use it there.

I do recommend before you start writing any code that you consider sorting your data (i.e., use sorted array and binary search) instead of constructing a tree.

**Comment by StarGazerM** [comment]
Thank you so much! I will look into it!
